Repository ubeac/svelte, pull requests merged in 2022-08, with the labels that each got.

#312 Feat card
  .storybook/stories/Card.stories.svelte
  src/components/card/Card.svelte
  src/components/card/CardFooter.svelte
  src/components/card/CardHeader.svelte
  src/components/card/CardStamp.svelte
  src/components/card/CardStatus.svelte
  src/components/card/CardSubtitle.svelte
  src/components/card/CardTitle.svelte
  src/components/card/card.types.ts
  src/scss/components/card.scss
Labels: Card

#313 #311 Radio and RadioGroup Fix Functionality
  .storybook/stories/Radio.stories.svelte
  src/components/radio/Radio.svelte
  src/components/radio/RadioGroup.svelte
  src/scss/components/input/radio-group.scss
  src/scss/components/input/radio.scss
Labels: test & debug

#309 #308 Implement Status Components
  .storybook/stories/Status.stories.svelte
  .vscode/settings.json
  src/components/index.ts
  src/components/status/Status.svelte
  src/components/status/index.ts
  src/scss/components/index.scss
  src/scss/components/status.scss
Labels: enhancement, proposal, test & debug

#316 #315 Status - Add prefix to status styles
  src/scss/components/status.scss
Labels: test & debug

#322 #238 Input component and scss enhancement
  .storybook/stories/Input.stories.svelte
  src/components/input/Input.svelte
  src/components/input/index.ts
  src/components/input/input.types.ts
  src/scss/components/input/input.scss
Labels: Input

#324 #246 Breadcrumb - Review functionality
  .storybook/stories/Breadcrumb.stories.svelte
  src/components/breadcrumbs/Breadcrumb.svelte
  src/scss/components/breadcrumbs.scss
Labels: documentation, test & debug

#320 #319 Accordion - add prefix variable to styles
  src/scss/components/accordion.scss
Labels: enhancement, test & debug

#329 #327 - Story source feature enabled
  .storybook/main.js
  package-lock.json
  package.json
Labels: Storybook

#332 #331 - Organizing Storybook sidebar
  .storybook/stories/Accordion.stories.svelte
  .storybook/stories/Alert.stories.svelte
  .storybook/stories/App.stories.svelte
  .storybook/stories/AppLoadingBar.stories.svelte
  .storybook/stories/Autocomplete.stories.svelte
  .storybook/stories/Avatar.stories.svelte
  .storybook/stories/AvatarGroup.stories.svelte
  .storybook/stories/Badge.stories.svelte
  .storybook/stories/Breadcrumb.stories.svelte
  .storybook/stories/BreadcrumbItem.stories.svelte
  .storybook/stories/Button.stories.svelte
  .storybook/stories/ButtonGroup.stories.svelte
  .storybook/stories/Card.stories.svelte
  .storybook/stories/Carousel.stories.svelte
  .storybook/stories/Checkbox.stories.svelte
  .storybook/stories/CheckboxGroup.stories.svelte
  .storybook/stories/Collapse.stories.svelte
  .storybook/stories/Confirm.stories.svelte
  .storybook/stories/DatePicker.stories.svelte
  .storybook/stories/Dialog.stories.svelte
  .storybook/stories/Divider.stories.svelte
  .storybook/stories/FormAutocomplete.stories.svelte
  .storybook/stories/FormCheckbox.stories.svelte
  .storybook/stories/FormDatePicker.stories.svelte
  .storybook/stories/FormFieldset.stories.svelte
  .storybook/stories/FormGroup.stories.svelte
  .storybook/stories/FormInput.stories.svelte
  .storybook/stories/FormRadio.stories.svelte
  .storybook/stories/FormSelect.stories.svelte
  .storybook/stories/FormSwitch.stories.svelte
  .storybook/stories/FormTextarea.stories.svelte
  .storybook/stories/GoogleMap.stories.svelte
  .storybook/stories/GoogleMapAutocomplete.stories.svelte
  .storybook/stories/Grid.stories.svelte
  .storybook/stories/GridItem.stories.svelte
  .storybook/stories/Icon.stories.svelte
  .storybook/stories/Input.stories.svelte
  .storybook/stories/Label.stories.svelte
  .storybook/stories/Menu.stories.svelte
  .storybook/stories/Popup.stories.svelte
  .storybook/stories/Radio.stories.svelte
  .storybook/stories/Select.stories.svelte
  .storybook/stories/Spinner.stories.svelte
  .storybook/stories/Status.stories.svelte
  .storybook/stories/Switch.stories.svelte
  .storybook/stories/Tab.stories.svelte
  .storybook/stories/Table.stories.svelte
  .storybook/stories/Textarea.stories.svelte
Labels: Storybook
