Repository ubeac/svelte, pull requests merged in 2023-01, with the labels that each got.

#807 make icon stroke widths similar to tabler icons
  src/scss/tabler/components/_icon.scss
Labels: Icon

#809 744 refactor el scss
  src/scss/tabler/_variables.scss
  src/scss/tabler/components.scss
  src/scss/tabler/components/_autocomplete.scss
  src/scss/tabler/components/_checkbox.scss
  src/scss/tabler/components/_date-picker.scss
  src/scss/tabler/components/_file-uploader.scss
  src/scss/tabler/components/_form-field.scss
  src/scss/tabler/components/_form-fieldset.scss
  src/scss/tabler/components/_input.scss
  src/scss/tabler/components/_radio.scss
  src/scss/tabler/components/_select.scss
  src/scss/tabler/components/_switch.scss
  src/scss/tabler/components/_textarea.scss
  src/scss/tabler/components/el.scss
  src/scss/tabler/components/form/form-hint.scss
  src/scss/tabler/components/form/index.scss
  src/scss/tabler/components/index.scss
  src/scss/tabler/components/input/index.scss
Labels: El

#812 fixed meta description and added title and description to home page
  src/routes/(docs)/docs/+layout.svelte
  src/routes/+page.svelte
Labels: documentation

#792 #787 - Remove FormHint component
  src/components/Form/FormHint.svelte
  src/components/Form/index.ts
Labels: FormHint

#827 #815 - Fix forward events error
  src/components/Popup/Popup.svelte
Labels: Popup

#820 Feat/813 lighthouse score
  src/components/Button/Button.svelte
  src/routes/+page.svelte
  src/routes/+page.ts
  src/routes/landing.css
  static/css/tabler.css
  static/images/svelte.png
  static/images/svelte.webp
  static/images/ubeac.png
  static/images/ubeac.webp
  svelte.config.js
Labels: documentation

#836 #800 - move tabler.css to npm package
  scripts/styles.generator.js
  src/styles/tabler.css
Labels: core

#835 added start and end to cardMedia and cleaned up card samples
  src/components/Card/Card.types.ts
  src/routes/(docs)/docs/components/cards/+page.svelte
  src/routes/(docs)/docs/components/cards/CardAside.svelte
  src/routes/(docs)/docs/components/cards/CardBlog.svelte
  src/routes/(docs)/docs/components/cards/CardBody.svelte
  src/routes/(docs)/docs/components/cards/CardColor.svelte
  src/routes/(docs)/docs/components/cards/CardFooter.svelte
  src/routes/(docs)/docs/components/cards/CardImage.svelte
  src/routes/(docs)/docs/components/cards/CardMedia.svelte
  src/routes/(docs)/docs/components/cards/CardTitle.svelte
  src/scss/tabler/components/_card.scss
Labels: Card

#838 #837 - support import of scss files
  svelte.config.js
Labels: documentation, core

#842 update dependencies and add svelte to peerDependency
  package.json
Labels: dependencies

#843 removed package sideEffects
  package.json
Labels: enhancement, dependencies

#851 #846 - support ssr
  .gitignore
  src/components/Carousel/Carousel.svelte
  src/components/Carousel/CarouselItem.svelte
  src/components/Input/Input.svelte
  src/docs-components/Doc.svelte
  src/docs-components/ToC.svelte
  src/routes/(docs)/+layout.svelte
  src/routes/(docs)/docs/components/carousel/CarouselAutoplay.svelte
  src/routes/(docs)/docs/components/carousel/CarouselDefault.svelte
  src/routes/(docs)/docs/components/carousel/CarouselNavigation.svelte
  src/routes/(docs)/docs/form/form-checkbox-groups/+page.svelte
  src/routes/(docs)/docs/form/form-textareas/+page.svelte
  src/routes/(docs)/docs/index.ts
  src/routes/+layout.ts
  src/styles/tabler.css
Labels: documentation

#854 fixed accessibility issues
  src/routes/(docs)/+layout.svelte
  src/routes/(docs)/docs/+page.svelte
Labels: documentation, enhancement

#864 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#865 696 update readme file
  README.md
  src/routes/(docs)/docs/+page.svelte
  src/routes/+page.svelte
Labels: documentation

#863 write some lines about how to install components in svelte and sveltekit projects
  src/routes/(docs)/docs/getting-started/installation/+page.svelte
Labels: documentation

#866 Next
  .prettierignore
  README.md
  package.json
Labels: documentation

#861 add description property for radio component
  src/components/Radio/Radio.svelte
  src/components/Radio/Radio.types.ts
  src/routes/(docs)/docs/components/radios/+page.svelte
  src/routes/(docs)/docs/components/radios/RadioDescription.svelte
  src/scss/tabler/components/_radio.scss
  src/styles/tabler.css
Labels: Radio

#858 Fix form autocomplete remote data example
  src/routes/(docs)/docs/form/form-autocompletes/+page.svelte
  src/routes/(docs)/docs/form/form-autocompletes/FormAutocompleteRemoteData.svelte
Labels: FormAutocomplete

#871 updated robots.txt file to let search engines to index only pages in …
  src/routes/(docs)/+layout.server.ts
  src/routes/(docs)/+layout.svelte
  src/routes/(docs)/docs/+layout.svelte
  src/routes/(docs)/docs/components/dialog/+page.svelte
  src/routes/(docs)/docs/components/radios/+page.svelte
  src/routes/(docs)/docs/components/ribbon/+page.svelte
  src/routes/(docs)/docs/components/spinners/+page.svelte
  src/routes/(docs)/docs/components/stamp/+page.svelte
  src/routes/(docs)/docs/index.ts
  src/routes/+page.svelte
  src/routes/robots.txt/+server.ts
Labels: documentation, enhancement

#891 fixed redirect issue and page meta tag issue on refresh
  src/routes/(docs)/+layout.server.ts
  src/routes/(docs)/+layout.svelte
  src/routes/(docs)/docs/+layout.svelte
  src/routes/(docs)/docs/index.ts
  src/routes/sitemap.xml/+server.ts
Labels: SEO

#893 Typo
  src/routes/(docs)/docs/index.ts
Labels: documentation

#896 #895 change default tag name (h2 to div) in AccordionHeader
  src/components/Accordion/AccordionHeader.svelte
Labels: enhancement, Accordion
